### ISSUE TITLE
View is not drawn properly when the height is smaller than the width

### ISSUE THREAD

**Issue by augusto-carmo-mesa** [augustocarmo/MesaIncPinEntry#1]
Part of the stroke gets cropped.

![image](https://user-images.githubusercontent.com/82174208/123700917-83bdff80-d837-11eb-9ce1-937693025858.png)

**Comment by augustocarmo** [comment]
Issue solved by overriding `onPreDraw()`:

```kt
override fun onPreDraw(): Boolean {
    return true
}
```
